plugins:
  discord_sync_enabled:
    default: true
    client: false
  discord_sync_token:
    default: ''
    client: false
  discord_sync_prefix:
    default: '!'
    client: false
  discord_sync_admin_channel_id:
    default: ''
    client: false
  discord_sync_public_channel_id:
    default: ''
    client: false
  discord_sync_username:
    default: true
    client: false
  discord_sync_verified_role:
    default: ''
    client: false
  discord_sync_safe_roles:
    default: 'Admins|Moderators'
    type: list
    list_type: compact
  discord_debug_enabled:
    default: false
    client: false