plugins:
  discord_sync_enabled:
    default: true
    client: false
  discord_sync_token:
    default: ''
    client: false
  discord_sync_prefix:
    default: '!'
    client: false
  discord_sync_admin_channel_id:
    default: ''
    client: false
